export const CURRENCIES = [
  { code: 'USD', symbol: '$', name: 'US Dollar', country: 'United States' },
  { code: 'EUR', symbol: '€', name: 'Euro', country: 'Eurozone' },
  { code: 'GBP', symbol: '£', name: 'Pound Sterling', country: 'United Kingdom' },
  { code: 'PKR', symbol: 'Rs', name: 'Pakistani Rupee', country: 'Pakistan' },
  { code: 'INR', symbol: '₹', name: 'Indian Rupee', country: 'India' },
  { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham', country: 'United Arab Emirates' },
  { code: 'SAR', symbol: '﷼', name: 'Saudi Riyal', country: 'Saudi Arabia' },
  { code: 'QAR', symbol: 'ر.ق', name: 'Qatari Riyal', country: 'Qatar' },
  { code: 'KWD', symbol: 'د.ك', name: 'Kuwaiti Dinar', country: 'Kuwait' },
  { code: 'BHD', symbol: '.د.ب', name: 'Bahraini Dinar', country: 'Bahrain' },
  { code: 'OMR', symbol: 'ر.ع.', name: 'Omani Rial', country: 'Oman' },
  { code: 'JPY', symbol: '¥', name: 'Japanese Yen', country: 'Japan' },
  { code: 'CNY', symbol: '¥', name: 'Chinese Yuan', country: 'China' },
  { code: 'KRW', symbol: '₩', name: 'South Korean Won', country: 'South Korea' },
  { code: 'CAD', symbol: '$', name: 'Canadian Dollar', country: 'Canada' },
  { code: 'AUD', symbol: '$', name: 'Australian Dollar', country: 'Australia' },
  { code: 'NZD', symbol: '$', name: 'New Zealand Dollar', country: 'New Zealand' },
  { code: 'CHF', symbol: 'Fr', name: 'Swiss Franc', country: 'Switzerland' },
  { code: 'SEK', symbol: 'kr', name: 'Swedish Krona', country: 'Sweden' },
  { code: 'NOK', symbol: 'kr', name: 'Norwegian Krone', country: 'Norway' },
  { code: 'DKK', symbol: 'kr', name: 'Danish Krone', country: 'Denmark' },
  { code: 'PLN', symbol: 'zł', name: 'Polish Zloty', country: 'Poland' },
  { code: 'CZK', symbol: 'Kč', name: 'Czech Koruna', country: 'Czech Republic' },
  { code: 'HUF', symbol: 'Ft', name: 'Hungarian Forint', country: 'Hungary' },
  { code: 'RON', symbol: 'lei', name: 'Romanian Leu', country: 'Romania' },
  { code: 'RUB', symbol: '₽', name: 'Russian Ruble', country: 'Russia' },
  { code: 'TRY', symbol: '₺', name: 'Turkish Lira', country: 'Turkey' },
  { code: 'ILS', symbol: '₪', name: 'Israeli Shekel', country: 'Israel' },
  { code: 'EGP', symbol: 'ج.م', name: 'Egyptian Pound', country: 'Egypt' },
  { code: 'ZAR', symbol: 'R', name: 'South African Rand', country: 'South Africa' },
  { code: 'NGN', symbol: '₦', name: 'Nigerian Naira', country: 'Nigeria' },
  { code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling', country: 'Kenya' },
  { code: 'GHS', symbol: '₵', name: 'Ghanaian Cedi', country: 'Ghana' },
  { code: 'MAD', symbol: 'د.م.', name: 'Moroccan Dirham', country: 'Morocco' },
  { code: 'TZS', symbol: 'TSh', name: 'Tanzanian Shilling', country: 'Tanzania' },
  { code: 'ETB', symbol: 'Br', name: 'Ethiopian Birr', country: 'Ethiopia' },
  { code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka', country: 'Bangladesh' },
  { code: 'LKR', symbol: 'Rs', name: 'Sri Lankan Rupee', country: 'Sri Lanka' },
  { code: 'NPR', symbol: 'Rs', name: 'Nepalese Rupee', country: 'Nepal' },
  { code: 'AFN', symbol: '؋', name: 'Afghan Afghani', country: 'Afghanistan' },
  { code: 'IRR', symbol: '﷼', name: 'Iranian Rial', country: 'Iran' },
  { code: 'IQD', symbol: 'ع.د', name: 'Iraqi Dinar', country: 'Iraq' },
  { code: 'JOD', symbol: 'د.ا', name: 'Jordanian Dinar', country: 'Jordan' },
  { code: 'LBP', symbol: 'ل.ل', name: 'Lebanese Pound', country: 'Lebanon' },
  { code: 'SYP', symbol: '£S', name: 'Syrian Pound', country: 'Syria' },
  { code: 'YER', symbol: '﷼', name: 'Yemeni Rial', country: 'Yemen' },
  { code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah', country: 'Indonesia' },
  { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit', country: 'Malaysia' },
  { code: 'SGD', symbol: '$', name: 'Singapore Dollar', country: 'Singapore' },
  { code: 'THB', symbol: '฿', name: 'Thai Baht', country: 'Thailand' },
  { code: 'PHP', symbol: '₱', name: 'Philippine Peso', country: 'Philippines' },
  { code: 'VND', symbol: '₫', name: 'Vietnamese Dong', country: 'Vietnam' },
  { code: 'MMK', symbol: 'K', name: 'Myanmar Kyat', country: 'Myanmar' },
  { code: 'KHR', symbol: '៛', name: 'Cambodian Riel', country: 'Cambodia' },
  { code: 'LAK', symbol: '₭', name: 'Lao Kip', country: 'Laos' },
  { code: 'HKD', symbol: '$', name: 'Hong Kong Dollar', country: 'Hong Kong' },
  { code: 'TWD', symbol: '$', name: 'New Taiwan Dollar', country: 'Taiwan' },
  { code: 'MXN', symbol: '$', name: 'Mexican Peso', country: 'Mexico' },
  { code: 'BRL', symbol: 'R$', name: 'Brazilian Real', country: 'Brazil' },
  { code: 'ARS', symbol: '$', name: 'Argentine Peso', country: 'Argentina' },
  { code: 'CLP', symbol: '$', name: 'Chilean Peso', country: 'Chile' },
  { code: 'COP', symbol: '$', name: 'Colombian Peso', country: 'Colombia' },
  { code: 'PEN', symbol: 'S/', name: 'Peruvian Sol', country: 'Peru' },
  { code: 'UYU', symbol: '$U', name: 'Uruguayan Peso', country: 'Uruguay' },
  { code: 'BOB', symbol: 'Bs.', name: 'Bolivian Boliviano', country: 'Bolivia' },
  { code: 'UAH', symbol: '₴', name: 'Ukrainian Hryvnia', country: 'Ukraine' },
  { code: 'KZT', symbol: '₸', name: 'Kazakhstani Tenge', country: 'Kazakhstan' },
  { code: 'UZS', symbol: "so'm", name: 'Uzbekistani Som', country: 'Uzbekistan' },
  { code: 'AZN', symbol: '₼', name: 'Azerbaijani Manat', country: 'Azerbaijan' },
  { code: 'GEL', symbol: '₾', name: 'Georgian Lari', country: 'Georgia' },
  { code: 'AMD', symbol: '֏', name: 'Armenian Dram', country: 'Armenia' },
  { code: 'ISK', symbol: 'kr', name: 'Icelandic Krona', country: 'Iceland' },
  { code: 'BGN', symbol: 'лв', name: 'Bulgarian Lev', country: 'Bulgaria' },
  { code: 'HRK', symbol: 'kn', name: 'Croatian Kuna', country: 'Croatia' },
  { code: 'RSD', symbol: 'дин.', name: 'Serbian Dinar', country: 'Serbia' },
  { code: 'ALL', symbol: 'L', name: 'Albanian Lek', country: 'Albania' },
  { code: 'MKD', symbol: 'ден', name: 'Macedonian Denar', country: 'North Macedonia' },
  { code: 'BAM', symbol: 'KM', name: 'Bosnia-Herzegovina Mark', country: 'Bosnia and Herzegovina' },
  { code: 'MDL', symbol: 'L', name: 'Moldovan Leu', country: 'Moldova' },
  { code: 'BYN', symbol: 'Br', name: 'Belarusian Ruble', country: 'Belarus' },
  { code: 'QRG', symbol: 'с', name: 'Kyrgyzstani Som', country: 'Kyrgyzstan' },
  { code: 'TJS', symbol: 'ЅМ', name: 'Tajikistani Somoni', country: 'Tajikistan' },
  { code: 'TMT', symbol: 'm', name: 'Turkmenistani Manat', country: 'Turkmenistan' },
  { code: 'MNT', symbol: '₮', name: 'Mongolian Tugrik', country: 'Mongolia' },
  { code: 'FJD', symbol: '$', name: 'Fijian Dollar', country: 'Fiji' },
  { code: 'PGK', symbol: 'K', name: 'Papua New Guinean Kina', country: 'Papua New Guinea' },
  { code: 'WST', symbol: 'T', name: 'Samoan Tala', country: 'Samoa' },
  { code: 'TOP', symbol: 'T$', name: 'Tongan Paʻanga', country: 'Tonga' },
  { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc', country: 'West Africa' },
  { code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc', country: 'Central Africa' },
  { code: 'XCD', symbol: '$', name: 'East Caribbean Dollar', country: 'Eastern Caribbean' },
  { code: 'DZD', symbol: 'د.ج', name: 'Algerian Dinar', country: 'Algeria' },
  { code: 'TND', symbol: 'د.ت', name: 'Tunisian Dinar', country: 'Tunisia' },
  { code: 'LYD', symbol: 'ل.د', name: 'Libyan Dinar', country: 'Libya' },
  { code: 'SDG', symbol: 'ج.س.', name: 'Sudanese Pound', country: 'Sudan' },
  { code: 'UGX', symbol: 'USh', name: 'Ugandan Shilling', country: 'Uganda' },
  { code: 'RWF', symbol: 'FRw', name: 'Rwandan Franc', country: 'Rwanda' },
  { code: 'ZMW', symbol: 'ZK', name: 'Zambian Kwacha', country: 'Zambia' },
  { code: 'MWK', symbol: 'MK', name: 'Malawian Kwacha', country: 'Malawi' },
  { code: 'MZN', symbol: 'MT', name: 'Mozambican Metical', country: 'Mozambique' },
  { code: 'BWP', symbol: 'P', name: 'Botswana Pula', country: 'Botswana' },
  { code: 'NAD', symbol: '$', name: 'Namibian Dollar', country: 'Namibia' },
  { code: 'SZL', symbol: 'L', name: 'Eswatini Lilangeni', country: 'Eswatini' },
  { code: 'LSL', symbol: 'L', name: 'Lesotho Loti', country: 'Lesotho' },
  { code: 'MUR', symbol: '₨', name: 'Mauritian Rupee', country: 'Mauritius' },
  { code: 'SCR', symbol: '₨', name: 'Seychellois Rupee', country: 'Seychelles' },
  { code: 'MVR', symbol: '.ރ', name: 'Maldivian Rufiyaa', country: 'Maldives' },
  { code: 'BTN', symbol: 'Nu.', name: 'Bhutanese Ngultrum', country: 'Bhutan' },
  { code: 'BND', symbol: '$', name: 'Brunei Dollar', country: 'Brunei' },
  { code: 'BMD', symbol: '$', name: 'Bermudian Dollar', country: 'Bermuda' },
  { code: 'JMD', symbol: '$', name: 'Jamaican Dollar', country: 'Jamaica' },
  { code: 'TTD', symbol: '$', name: 'Trinidad and Tobago Dollar', country: 'Trinidad and Tobago' },
  { code: 'BBD', symbol: '$', name: 'Barbadian Dollar', country: 'Barbados' },
  { code: 'BSD', symbol: '$', name: 'Bahamian Dollar', country: 'Bahamas' },
  { code: 'BZD', symbol: 'BZ$', name: 'Belize Dollar', country: 'Belize' },
  { code: 'GTQ', symbol: 'Q', name: 'Guatemalan Quetzal', country: 'Guatemala' },
  { code: 'HNL', symbol: 'L', name: 'Honduran Lempira', country: 'Honduras' },
  { code: 'NIO', symbol: 'C$', name: 'Nicaraguan Cordoba', country: 'Nicaragua' },
  { code: 'CRC', symbol: '₡', name: 'Costa Rican Colon', country: 'Costa Rica' },
  { code: 'PAB', symbol: 'B/.', name: 'Panamanian Balboa', country: 'Panama' },
  { code: 'DOP', symbol: 'RD$', name: 'Dominican Peso', country: 'Dominican Republic' },
  { code: 'HTG', symbol: 'G', name: 'Haitian Gourde', country: 'Haiti' },
  { code: 'CUP', symbol: '$', name: 'Cuban Peso', country: 'Cuba' },
  { code: 'PYG', symbol: '₲', name: 'Paraguayan Guarani', country: 'Paraguay' },
  { code: 'VES', symbol: 'Bs.', name: 'Venezuelan Bolivar', country: 'Venezuela' },
  { code: 'GYD', symbol: '$', name: 'Guyanese Dollar', country: 'Guyana' },
  { code: 'SRD', symbol: '$', name: 'Surinamese Dollar', country: 'Suriname' },
]
